In [1]:
import pandas as pd 
import numpy as np
mydata= pd.read_csv("C:/Users/Mohsen/Desktop/Wednesday-workingHours.pcap_ISCX.csv")
#Constructing DataFrame
mydata=pd.DataFrame(data=mydata)    
# Create a reproducible sample using random_state
mydata = mydata.sample(n = 1000, random_state = 1)


In [2]:
# IS THERE ANY MISSING DATA?
mydata.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
Label                          0
Length: 79, dtype: int64

In [3]:
mydata = mydata.replace(['BENIGN'],'0')
mydata=mydata.replace(['DoS Hulk'],'1')
mydata=mydata.replace(['DoS GoldenEye'],'1')
mydata=mydata.replace(['DoS slowloris'],'1')
mydata=mydata.replace(['DoS Slowhttptest'],'1')
mydata=mydata.replace(['Heartbleed'],'1')
   

In [4]:
mydata.describe()

Destination Port   Flow Duration   Total Fwd Packets  \
count        1000.000000    1.000000e+03         1000.000000   
mean         5314.911000    2.713930e+07            6.119000   
std         15495.989176    4.260360e+07           13.994738   
min            21.000000    1.000000e+00            1.000000   
25%            53.000000    2.147500e+02            2.000000   
50%            80.000000    5.019950e+04            2.000000   
75%           443.000000    6.785736e+07            7.000000   
max         61674.000000    1.199921e+08          247.000000   

        Total Backward Packets  Total Length of Fwd Packets  \
count              1000.000000                  1000.000000   
mean                  5.567000                   806.090000   
std                  19.083965                  4212.244067   
min                   0.000000                     0.000000   
25%                   1.000000                    12.000000   
50%                   2.000000                    82.000000   
75%                   6.000000                   362.000000   
max                 314.000000                 71099.000000   

        Total Length of Bwd Packets   Fwd Packet Length Max  \
count                   1000.000000             1000.000000   
mean                    6033.001000              276.947000   
std                    32448.602247              708.779407   
min                        0.000000                0.000000   
25%                        0.000000                6.000000   
50%                      180.000000               46.000000   
75%                     6627.250000              338.000000   
max                   644940.000000             7240.000000   

        Fwd Packet Length Min   Fwd Packet Length Mean  \
count             1000.000000              1000.000000   
mean                15.280000                69.934195   
std                 45.082569               192.928192   
min                  0.000000                 0.000000   
25%                  0.000000                 6.000000   
50%                  0.000000                40.774854   
75%                 33.000000                56.468750   
max               1236.000000              1932.500000   

        Fwd Packet Length Std  ...   act_data_pkt_fwd   min_seg_size_forward  \
count             1000.000000  ...        1000.000000            1000.000000   
mean                93.884148  ...           3.255000              27.132000   
std                250.504832  ...          13.304096               6.314939   
min                  0.000000  ...           0.000000              20.000000   
25%                  0.000000  ...           0.000000              20.000000   
50%                  0.000000  ...           1.000000              32.000000   
75%                128.404463  ...           2.000000              32.000000   
max               3126.682571  ...         246.000000              44.000000   

        Active Mean    Active Std    Active Max    Active Min     Idle Mean  \
count  1.000000e+03  1.000000e+03  1.000000e+03  1.000000e+03  1.000000e+03   
mean   9.883811e+04  6.635167e+04  1.898070e+05  5.474059e+04  2.064734e+07   
std    6.457519e+05  5.744676e+05  1.225259e+06  4.612285e+05  3.698749e+07   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    9.830000e+02  0.000000e+00  9.830000e+02  9.697500e+02  1.000000e+07   
max    1.100000e+07  1.220000e+07  2.540000e+07  7.407733e+06  1.180000e+08   

           Idle Std      Idle Max      Idle Min  
count  1.000000e+03  1.000000e+03  1.000000e+03  
mean   3.372270e+05  2.098641e+07  2.036773e+07  
std    3.612298e+06  3.725865e+07  3.696734e+07  
min    0.000000e+00  0.000000e+00  0.000000e+00  
25%    0.000000e+00  0.000000e+00  0.000000e+00  
50%    0.000000e+00  0.000000e+00  0.00

In [5]:
mydata.head(10)

Destination Port   Flow Duration   Total Fwd Packets  \
560699                 53             213                   2   
538462                 53           31082                   4   
626316                 53             295                   2   
310282                 80           24610                   2   
485771                 53        19177137                   2   
676471                 53           31367                   2   
144377                 80               3                   2   
261448                 80        98196159                   6   
282145                 80        85745147                   8   
108045                 80           98509                   3   

         Total Backward Packets  Total Length of Fwd Packets  \
560699                        2                          144   
538462                        4                          188   
626316                        2                          102   
310282                        0                            0   
485771                        2                          119   
676471                        2                           60   
144377                        0                            0   
261448                        6                          369   
282145                        7                          314   
108045                        6                          311   

         Total Length of Bwd Packets   Fwd Packet Length Max  \
560699                           400                      72   
538462                           536                      47   
626316                           306                      51   
310282                             0                       0   
485771                           318                      61   
676471                           252                      30   
144377                             0                       0   
261448                         11595                     369   
282145                         11595                     314   
108045                         11595                     311   

         Fwd Packet Length Min   Fwd Packet Length Mean  \
560699                      72                72.000000   
538462                      47                47.000000   
626316                      51                51.000000   
310282                       0                 0.000000   
485771                      58                59.500000   
676471                      30                30.000000   
144377                       0                 0.000000   
261448                       0                61.500000   
282145                       0                39.250000   
108045                       0               103.666667   

         Fwd Packet Length Std  ...   min_seg_size_forward  Active Mean  \
560699                0.000000  ...                     32          0.0   
538462                0.000000  ...                     20          0.0   
626316                0.000000  ...                     20          0.0   
310282                0.000000  ...                     32          0.0   
485771                2.121320  ...                     20     127387.0   
676471                0.000000  ...                     32          0.0   
144377                0.000000  ...                     32          0.0   
261448              150.643619  ...                     32        981.0   
282145              111.015765  ...                     32        593.0   
108045              179.555934  ...                     32          0.0   

         Active Std   Active Max   Active Min   Idle Mean   Idle Std  \
560699          0.0            0            0         0.0        0.0   
538462          0.0            0            0         0.0        0.0   
626316          0.0            0            0         0.0        0.0   
310282          0.0            0            0         0.0        0.0   
485771          0.0       127387       127387  

In [6]:
mydata=mydata.dropna()

In [7]:
X = mydata.drop('Label', 1)
y = mydata['Label']

In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
from sklearn.decomposition import PCA
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [10]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [11]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print( accuracy_score(y_test, y_pred))




[[115   0]
 [ 45  40]]
[[115   0]
 [ 45  40]]
0.775


In [13]:
# Initialize the logistic regression model
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(max_iter=2500)

# Train the model
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test) # Predictions
y_true = y_test # True values
# Measure accuracy
from sklearn import metrics
from sklearn.metrics import accuracy_score
import numpy as np
print("Train accuracy:", np.round(accuracy_score(y_train,clf.predict(X_train)), 2))
print("Test accuracy:", np.round(accuracy_score(y_true, y_pred), 2))


Train accuracy: 0.84
Test accuracy: 0.78


In [16]:
# Neural Network
# Neural Network
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
model = mlp.fit(X_train,y_train)
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))
# Area under curve
print("area under curve (auc): ", metrics.roc_auc_score(y_test, y_pred))

[[492  36]
 [105 167]]
              precision    recall  f1-score   support

           0       0.82      0.93      0.87       528
           1       0.82      0.61      0.70       272

    accuracy                           0.82       800
   macro avg       0.82      0.77      0.79       800
weighted avg       0.82      0.82      0.82       800

area under curve (auc):  0.7398976982097187
